"""Deterministic pytest-Playwright source generation and validation."""

from __future__ import annotations

import ast
import json
import os
import re
import subprocess
import tempfile
from pathlib import Path

from qualityproof.models import (
    ActionEdge,
    ApiAssertion,
    AriaSnapshotAssertion,
    ClickStep,
    FillStep,
    Locator,
    LocatorStrategy,
    NavigateStep,
    PageState,
    PressStep,
    Requirement,
    ScenarioSpec,
    ScenarioStatus,
    TextAssertion,
    TitleAssertion,
    UrlAssertion,
    VisibleAssertion,
)
from qualityproof.repository import SQLiteRepository
from qualityproof.scenarios import (
    mine_scenarios,
    read_scenario,
    requires_discovery_validation,
    validate_model_proposals,
    validate_scenario_policy,
)

HEADER = (
    "# Generated by QualityProof from approved scenario YAML.\n"
    "# DO NOT EDIT: regenerate with `qualityproof generate`.\n"
)
MANIFEST_NAME = "qualityproof-generation-manifest.json"
DOCSTRING_LINE = '    """Execute the approved QualityProof scenario."""'
CONFTEST_NAME = "conftest.py"
CONFTEST_SOURCE = '''# Generated by QualityProof. DO NOT EDIT.
"""Fixture wiring for the generated suite.

Behaviour lives in ``qualityproof.fixtures`` so that generated tests stay pure
intent: what to visit and what must hold. Determinism, authentication, timeouts
and artifact policy are supplied here, once, for every test.
"""

from qualityproof.fixtures import *  # noqa: F401,F403
from qualityproof.fixtures import pytest_runtest_makereport  # noqa: F401
'''


def _identifier(value: str) -> str:
    normalized = re.sub(r"\W+", "_", value.casefold()).strip("_")
    if not normalized or normalized[0].isdigit():
        normalized = f"scenario_{normalized}"
    return normalized


def python_locator(locator: Locator) -> str:
    """Render a locator as pytest-Playwright source, preferring user-facing calls.

    Playwright's own guidance is to resolve elements the way a user perceives
    them. Emitting ``get_by_role`` also makes the generated suite survive the
    exact defect class this project measures: a control whose CSS hook is renamed
    while its role and accessible name are unchanged.
    """
    if locator.strategy is LocatorStrategy.ROLE:
        return f"page.get_by_role({locator.role!r}, name={locator.name!r})"
    if locator.strategy is LocatorStrategy.TEST_ID:
        return f"page.get_by_test_id({locator.value!r})"
    if locator.strategy is LocatorStrategy.LABEL:
        return f"page.get_by_label({locator.value!r}, exact={locator.exact!r})"
    if locator.strategy is LocatorStrategy.PLACEHOLDER:
        return f"page.get_by_placeholder({locator.value!r}, exact={locator.exact!r})"
    if locator.strategy is LocatorStrategy.TEXT:
        return f"page.get_by_text({locator.value!r}, exact={locator.exact!r})"
    return f"page.locator({locator.css!r})"


LINE_BUDGET = 96


def _literal_entry(key: str, value: str, indent: str) -> list[str]:
    """Render one ``key: value`` pair, wrapping values that would overrun.

    Mined provenance locators are join-delimited page-state signatures and can be
    arbitrarily long, so a single-line dict entry breaks the line-length rule that
    the generated file is then checked against. Wrapping uses implicit string
    concatenation, which ``ast.literal_eval`` resolves back to one value, so the
    auditor still reads it without importing anything.
    """
    single = f"{indent}{key!r}: {value!r},"
    if len(single) <= LINE_BUDGET:
        return [single]
    budget = max(24, LINE_BUDGET - len(indent) - 8)
    chunks = [value[index : index + budget] for index in range(0, len(value), budget)]
    lines = [f"{indent}{key!r}: ("]
    lines.extend(f"{indent}    {chunk!r}" for chunk in chunks)
    lines.append(f"{indent}),")
    return lines


def _metadata_decorator(scenario: ScenarioSpec) -> tuple[str, ...]:
    """Emit the traceability decorator a generated test needs to be auditable.

    Without this the generated suite is invisible to the ledger: the auditor finds
    assertions but no requirement link or provenance, so every generated test
    classifies as UNKNOWN and the generate-to-audit edge of the pipeline does
    nothing. Values are rendered as plain literals because the auditor reads them
    with ``ast.literal_eval`` and never imports the module.
    """
    if not scenario.requirement_ids and not scenario.provenance:
        return ()
    lines = ["@qualityproof("]
    if scenario.requirement_ids:
        rendered = ", ".join(repr(item) for item in scenario.requirement_ids)
        if len(rendered) + 20 <= LINE_BUDGET:
            lines.append(f"    requirements=[{rendered}],")
        else:
            lines.append("    requirements=[")
            lines.extend(f"        {item!r}," for item in scenario.requirement_ids)
            lines.append("    ],")
    if scenario.provenance:
        lines.append("    provenance=[")
        for item in scenario.provenance:
            fields = [("kind", item.kind.value), ("source", item.source)]
            if item.locator is not None:
                fields.append(("locator", item.locator))
            if item.content_hash is not None:
                fields.append(("content_hash", item.content_hash))
            if item.approved_by is not None:
                fields.append(("approved_by", item.approved_by))
            if item.approved_at is not None:
                fields.append(("approved_at", item.approved_at.isoformat()))
            lines.append("        {")
            for key, value in fields:
                lines.extend(_literal_entry(key, value, "            "))
            lines.append("        },")
        lines.append("    ],")
    lines.append(")")
    return tuple(lines)


def _contract_comment(locator: Locator) -> tuple[str, ...]:
    """Record the CSS the element was discovered under, without depending on it."""
    if locator.strategy is LocatorStrategy.CSS or not locator.css:
        return ()
    return (f"    # contract: {locator.css}",)


def emit_pytest(scenario: ScenarioSpec, source: Path) -> str:
    if scenario.status is not ScenarioStatus.APPROVED:
        raise ValueError(f"scenario {scenario.id} is not approved")
    validate_scenario_policy(scenario)
    # An API assertion resolves through the api_request_context fixture, so the
    # test must request it. Emitting the call without the parameter produced a
    # NameError that no demo scenario happened to trigger.
    needs_api = any(isinstance(item, ApiAssertion) for item in scenario.assertions)
    if needs_api:
        playwright_import = "from playwright.sync_api import APIRequestContext, Page, expect"
    elif scenario.assertions:
        playwright_import = "from playwright.sync_api import Page, expect"
    else:
        playwright_import = "from playwright.sync_api import Page"
    arguments = (
        "page: Page, api_request_context: APIRequestContext" if needs_api else "page: Page"
    )
    metadata = _metadata_decorator(scenario)
    lines = [
        HEADER.rstrip(),
        f"# Source: {source.as_posix()}",
        "",
        playwright_import,
        *(("", "from qualityproof import qualityproof") if metadata else ()),
        "",
        "",
        *metadata,
        f"def test_{_identifier(scenario.id)}({arguments}) -> None:",
        DOCSTRING_LINE,
    ]
    for step in scenario.steps:
        if isinstance(step, NavigateStep):
            lines.extend(
                (
                    "    page.goto(",
                    f"        {step.url!r},",
                    "        wait_until='domcontentloaded',",
                    "    )",
                )
            )
        elif isinstance(step, ClickStep):
            lines.extend(_contract_comment(step.locator))
            lines.append(f"    {python_locator(step.locator)}.click()")
        elif isinstance(step, FillStep):
            lines.extend(_contract_comment(step.locator))
            lines.append(f"    {python_locator(step.locator)}.fill({step.value!r})")
        elif isinstance(step, PressStep):
            lines.extend(_contract_comment(step.locator))
            lines.append(f"    {python_locator(step.locator)}.press({step.key!r})")
    for assertion in scenario.assertions:
        expect_call = "expect.soft" if assertion.soft else "expect"
        if isinstance(assertion, VisibleAssertion):
            lines.extend(_contract_comment(assertion.locator))
            lines.append(
                f"    {expect_call}({python_locator(assertion.locator)}).to_be_visible()"
            )
        elif isinstance(assertion, TextAssertion):
            lines.extend(_contract_comment(assertion.locator))
            lines.extend(
                (
                    f"    {expect_call}({python_locator(assertion.locator)}).to_contain_text(",
                    f"        {assertion.expected!r}",
                    "    )",
                )
            )
        elif isinstance(assertion, AriaSnapshotAssertion):
            lines.extend(_contract_comment(assertion.locator))
            lines.extend(
                (
                    f"    {expect_call}({python_locator(assertion.locator)})"
                    ".to_match_aria_snapshot(",
                    f"        {assertion.expected!r}",
                    "    )",
                )
            )
        elif isinstance(assertion, ApiAssertion):
            lines.extend(
                (
                    f"    response = api_request_context.get({assertion.path!r})",
                    f"    {expect_call}(response).to_be_ok()"
                    if assertion.expected_status < 400
                    else f"    assert response.status == {assertion.expected_status}",
                )
            )
        elif isinstance(assertion, UrlAssertion):
            lines.append(f"    {expect_call}(page).to_have_url({assertion.expected!r})")
        elif isinstance(assertion, TitleAssertion):
            lines.append(f"    {expect_call}(page).to_have_title({assertion.expected!r})")
    return "\n".join(lines) + "\n"


TS_HEADER = (
    "// Generated by QualityProof from approved scenario YAML.\n"
    "// DO NOT EDIT: regenerate with `qualityproof generate --language typescript`.\n"
)


def _ts_string(value: str) -> str:
    """Render a JSON-safe TypeScript string literal."""
    return json.dumps(value, ensure_ascii=False)


def typescript_locator(locator: Locator) -> str:
    """Render a locator as Playwright Test source.

    Mirrors :func:`python_locator` deliberately: the same approved scenario must
    describe the same element in either language, otherwise "language-neutral"
    is a claim rather than a property.
    """
    if locator.strategy is LocatorStrategy.ROLE:
        role = _ts_string(str(locator.role))
        name = _ts_string(str(locator.name))
        return f"page.getByRole({role}, {{ name: {name} }})"
    if locator.strategy is LocatorStrategy.TEST_ID:
        return f"page.getByTestId({_ts_string(str(locator.value))})"
    if locator.strategy is LocatorStrategy.LABEL:
        return (
            f"page.getByLabel({_ts_string(str(locator.value))}, "
            f"{{ exact: {str(locator.exact).lower()} }})"
        )
    if locator.strategy is LocatorStrategy.PLACEHOLDER:
        return (
            f"page.getByPlaceholder({_ts_string(str(locator.value))}, "
            f"{{ exact: {str(locator.exact).lower()} }})"
        )
    if locator.strategy is LocatorStrategy.TEXT:
        return (
            f"page.getByText({_ts_string(str(locator.value))}, "
            f"{{ exact: {str(locator.exact).lower()} }})"
        )
    return f"page.locator({_ts_string(str(locator.css))})"


def _ts_contract(locator: Locator, indent: str) -> tuple[str, ...]:
    if locator.strategy is LocatorStrategy.CSS or not locator.css:
        return ()
    return (f"{indent}// contract: {locator.css}",)


def emit_playwright_typescript(scenario: ScenarioSpec, source: Path) -> str:
    """Emit a Playwright Test spec carrying the scenario's requirement annotations."""
    if scenario.status is not ScenarioStatus.APPROVED:
        raise ValueError(f"scenario {scenario.id} is not approved")
    validate_scenario_policy(scenario)
    annotations = [
        f'    {{ type: "requirement", description: {_ts_string(requirement)} }},'
        for requirement in scenario.requirement_ids
    ]
    for item in scenario.provenance:
        annotations.append(
            f'    {{ type: "provenance", description: '
            f"{_ts_string(f'{item.kind.value}:{item.source}')} }},"
        )
    lines = [
        TS_HEADER.rstrip(),
        f"// Source: {source.as_posix()}",
        "",
        'import { expect, test } from "@qualityproof/playwright";',
        "",
        f"test({_ts_string(scenario.title)}, {{",
        "  annotation: [",
        *annotations,
        "  ],",
        "}, async ({ page }) => {",
    ]
    for step in scenario.steps:
        if isinstance(step, NavigateStep):
            lines.append(
                f"  await page.goto({_ts_string(step.url)}, "
                '{ waitUntil: "domcontentloaded" });'
            )
        elif isinstance(step, ClickStep):
            lines.extend(_ts_contract(step.locator, "  "))
            lines.append(f"  await {typescript_locator(step.locator)}.click();")
        elif isinstance(step, FillStep):
            lines.extend(_ts_contract(step.locator, "  "))
            lines.append(
                f"  await {typescript_locator(step.locator)}.fill({_ts_string(step.value)});"
            )
        elif isinstance(step, PressStep):
            lines.extend(_ts_contract(step.locator, "  "))
            lines.append(
                f"  await {typescript_locator(step.locator)}.press({_ts_string(step.key)});"
            )
    for assertion in scenario.assertions:
        call = "expect.soft" if assertion.soft else "expect"
        if isinstance(assertion, VisibleAssertion):
            lines.extend(_ts_contract(assertion.locator, "  "))
            lines.append(
                f"  await {call}({typescript_locator(assertion.locator)}).toBeVisible();"
            )
        elif isinstance(assertion, TextAssertion):
            lines.extend(_ts_contract(assertion.locator, "  "))
            lines.append(
                f"  await {call}({typescript_locator(assertion.locator)})"
                f".toContainText({_ts_string(assertion.expected)});"
            )
        elif isinstance(assertion, AriaSnapshotAssertion):
            lines.extend(_ts_contract(assertion.locator, "  "))
            lines.append(
                f"  await {call}({typescript_locator(assertion.locator)})"
                f".toMatchAriaSnapshot({_ts_string(assertion.expected)});"
            )
        elif isinstance(assertion, ApiAssertion):
            lines.append(
                f"  const response = await request.get({_ts_string(assertion.path)});"
            )
            lines.append(
                f"  {call}(response.status()).toBe({assertion.expected_status});"
            )
        elif isinstance(assertion, UrlAssertion):
            lines.append(f"  await {call}(page).toHaveURL({_ts_string(assertion.expected)});")
        elif isinstance(assertion, TitleAssertion):
            lines.append(f"  await {call}(page).toHaveTitle({_ts_string(assertion.expected)});")
    lines.append("});")
    return "\n".join(lines) + "\n"


EMITTERS = {
    "python": ("test_", ".py", emit_pytest),
    "typescript": ("", ".spec.ts", emit_playwright_typescript),
}


def validate_generated(path: Path, project: Path) -> None:
    source = path.read_text(encoding="utf-8")
    ast.parse(source, filename=str(path))
    checks = (
        ["ruff", "check", str(path)],
        ["pytest", "--collect-only", "-q", str(path)],
    )
    for command in checks:
        result = subprocess.run(
            command,
            cwd=project,
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode:
            raise RuntimeError(
                f"{' '.join(command)} failed:\n{result.stdout}{result.stderr}".strip()
            )


def validate_typescript(path: Path, project: Path) -> None:
    """Type-check a generated spec when a Node toolchain is available.

    Absence of ``node_modules`` is recorded rather than fatal: emitting a spec
    must not require every contributor to install a JavaScript toolchain, but a
    skipped check is never silently reported as a passing one.
    """
    package = project / "packages" / "qualityproof-playwright"
    compiler = package / "node_modules" / "typescript" / "bin" / "tsc"
    if not compiler.is_file():
        return
    result = subprocess.run(
        ["node", str(compiler), "--noEmit", "--skipLibCheck", str(path)],
        cwd=package,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode:
        raise RuntimeError(f"tsc failed:\n{result.stdout}{result.stderr}".strip())


def reconcile_generated(
    project: Path,
    sources: tuple[Path, ...],
    destination: Path,
    *,
    filename_prefix: str = "test_",
    validate: bool = True,
    language: str = "python",
) -> tuple[Path, ...]:
    """Atomically publish one generated set and remove only manifest-owned stale files."""
    destination.mkdir(parents=True, exist_ok=True)
    manifest_path = destination / MANIFEST_NAME
    previous: dict[str, object] = {}
    if manifest_path.exists():
        loaded = json.loads(manifest_path.read_text(encoding="utf-8"))
        if not isinstance(loaded, dict):
            raise ValueError("generation manifest must contain an object")
        previous = loaded
    previous_outputs = previous.get("outputs", [])
    if not isinstance(previous_outputs, list) or not all(
        isinstance(item, str) for item in previous_outputs
    ):
        raise ValueError("generation manifest outputs must be strings")

    if language not in EMITTERS:
        raise ValueError(f"language must be one of {', '.join(sorted(EMITTERS))}")
    default_prefix, suffix, emitter = EMITTERS[language]
    prefix = filename_prefix if language == "python" else default_prefix
    rendered: list[tuple[Path, str]] = []
    for source in sources:
        scenario = read_scenario(source)
        output = destination / f"{prefix}{_identifier(scenario.id)}{suffix}"
        rendered.append((output, emitter(scenario, source.relative_to(project))))

    temporary_paths: list[Path] = []
    try:
        for output, content in rendered:
            with tempfile.NamedTemporaryFile(
                mode="w",
                encoding="utf-8",
                dir=destination,
                prefix=f"_qp_tmp_{output.stem}_",
                suffix=suffix,
                delete=False,
            ) as temporary:
                temporary.write(content)
                temporary_path = Path(temporary.name)
            temporary_paths.append(temporary_path)
            if validate and language == "python":
                validate_generated(temporary_path, project)
            elif validate:
                validate_typescript(temporary_path, project)
        for temporary_path, (output, _) in zip(temporary_paths, rendered, strict=True):
            os.replace(temporary_path, output)
        temporary_paths.clear()

        current_names = {output.name for output, _ in rendered}
        for stale_name in sorted(set(previous_outputs) - current_names):
            stale = destination / stale_name
            if (
                stale.parent == destination
                and stale.name.startswith(prefix)
                and stale.name.endswith(suffix)
            ):
                stale.unlink(missing_ok=True)
        manifest = {
            "schema_version": "qualityproof-generation-manifest/v1",
            "outputs": sorted(current_names),
            "sources": sorted(source.relative_to(project).as_posix() for source in sources),
            "language": language,
        }
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=destination,
            prefix=".manifest.",
            delete=False,
        ) as temporary:
            json.dump(manifest, temporary, indent=2, sort_keys=True)
            temporary.write("\n")
            temporary_manifest = Path(temporary.name)
        os.replace(temporary_manifest, manifest_path)
    finally:
        for temporary_path in temporary_paths:
            temporary_path.unlink(missing_ok=True)
    return tuple(output for output, _ in rendered)


def write_conftest(destination: Path) -> Path:
    """Publish the fixture wiring next to the generated tests."""
    destination.mkdir(parents=True, exist_ok=True)
    path = destination / CONFTEST_NAME
    if not path.exists() or path.read_text(encoding="utf-8") != CONFTEST_SOURCE:
        path.write_text(CONFTEST_SOURCE, encoding="utf-8")
    return path


def generate_approved(
    project: Path,
    *,
    validate: bool = True,
    repository: SQLiteRepository | None = None,
    language: str = "python",
) -> tuple[Path, ...]:
    approved = project / "scenarios" / "generated" / "approved"
    destination = (
        project / ".qualityproof" / "generated"
        if language == "python"
        else project / ".qualityproof" / "generated-typescript"
    )
    sources = tuple(sorted(approved.glob("*.yaml")))
    scenarios = tuple(read_scenario(source) for source in sources)
    model_scenarios = tuple(
        scenario for scenario in scenarios if requires_discovery_validation(scenario)
    )
    if model_scenarios:
        if repository is None:
            raise ValueError("model scenarios require persisted discovery validation")
        pages = repository.list("page_state", PageState)
        # Requirements must be passed through. Re-mining without them produced
        # candidates with empty requirement_ids, so every requirement-linked model
        # scenario failed as having "substituted persisted requirement
        # associations" — the gate rejected valid input and had never fired
        # successfully.
        candidates = mine_scenarios(
            pages,
            repository.list("action_edge", ActionEdge),
            repository.list("requirement", Requirement),
        )
        validate_model_proposals(model_scenarios, candidates, pages)
    if language == "python":
        write_conftest(destination)
    return reconcile_generated(
        project,
        sources,
        destination,
        validate=validate,
        language=language,
    )
